In [1]:
import torch
import numpy as np

In [3]:
# 1. Initializing a Tensor

# Directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
# From a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [11]:
# From another tensor
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor: \n {x_ones}')

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random Tensor: \n {x_rand}')

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])
Random Tensor: 
 tensor([[0.2635, 0.1858],
        [0.9609, 0.8979]])


In [27]:
# With random or constant values
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f'Random Tensor: \n {rand_tensor}')
print(f'Ones Tensor: \n {ones_tensor}')
print(f'Zeros Tensor: \n {zeros_tensor}')

Random Tensor: 
 tensor([[0.3954, 0.8576, 0.4671],
        [0.2166, 0.7137, 0.9727]])
Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [28]:
# 2. Attributes of Tensor

tensor = torch.rand(3, 4)

print(f'Shape of tensor: {tensor.shape}')
print(f'Datashape of tensor: {tensor.dtype}')
print(f'Device of tensor: {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datashape of tensor: torch.float32
Device of tensor: cpu


In [31]:
# 3. Operations on Tensors

# Over 100 operations including arithmetic, linear algebra, matrix manipulation(transposing, indexing, slicing), sampling, ...
if torch.cuda.is_available():
    print('Cuda is available')
    tensor = tensor.to('cuda')

In [32]:
# Standard numpy-like indexing and slicing

tensor = torch.ones(4, 4)
print(f'First row of tensor: {tensor[0]}')
print(f'First column of tensor: {tensor[:, 0]}')
print(f'Last column of tensor: {tensor[..., -1]}')
tensor[:, 1] = 0
print(tensor)

First row of tensor: tensor([1., 1., 1., 1.])
First column of tensor: tensor([1., 1., 1., 1.])
Last column of tensor: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [38]:
# Joining tensors

torch_cat = torch.cat([tensor, tensor, tensor, tensor], dim=1)
torch_cat

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [57]:
# Arithmetic operations

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [60]:
# Single-element tensors

agg = tensor.sum()
agg_item = agg.item()
print(agg, agg_item, type(agg_item))

tensor(12.) 12.0 <class 'float'>


In [63]:
# In-place operations

print(f'{tensor} \n')
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


In [ ]:
# 4. Bridge with NumPy

# Tensor to NumPy array